@if (Auth::user()->roles_id== '1')
    @include('layouts.sidebar.superadmin')
@elseif (Auth::user()->roles_id== '2')
    @include('layouts.sidebar.manajersite')
    @elseif (Auth::user()->roles_id== '4')
    @include('layouts.sidebar.customer')
@elseif (Auth::user()->roles_id== '5')
    @include('layouts.sidebar.customer')
    @elseif (Auth::user()->roles_id== '6')
    @include('layouts.sidebar.customer')

    @elseif (Auth::user()->roles_id== '100')
    @include('layouts.sidebar.hosparepart')
    @elseif (Auth::user()->roles_id== '101')
    @include('layouts.sidebar.inventory')
@endif
